CREATE TABLE IF NOT EXISTS `owner_bill_payment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `bill_id` bigint NOT NULL COMMENT '业主账单ID',
  `owner_id` bigint NOT NULL COMMENT '业主ID',
  `contract_id` bigint NOT NULL COMMENT '业主合同ID',
  `payment_no` varchar(64) NOT NULL COMMENT '付款单号',
  `pay_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '付款金额',
  `pay_time` datetime NOT NULL COMMENT '付款时间',
  `pay_channel` varchar(32) NOT NULL COMMENT '付款渠道',
  `third_trade_no` varchar(128) DEFAULT NULL COMMENT '第三方流水号',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_bill_payment_no` (`payment_no`),
  KEY `idx_owner_bill_payment_company` (`company_id`),
  KEY `idx_owner_bill_payment_bill` (`bill_id`),
  KEY `idx_owner_bill_payment_owner` (`owner_id`),
  KEY `idx_owner_bill_payment_contract` (`contract_id`),
  KEY `idx_owner_bill_payment_time` (`pay_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主账单付款记录表';
