SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `owner` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `owner_type_id` bigint NOT NULL COMMENT '业主类型关联ID',
  `owner_type` int NOT NULL COMMENT '业主类型：0=个人，1=企业',
  `owner_name` varchar(128) NOT NULL COMMENT '业主名称',
  `owner_phone` varchar(32) DEFAULT NULL COMMENT '联系电话',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_company` (`company_id`),
  KEY `idx_owner_type` (`owner_type`,`owner_type_id`),
  KEY `idx_owner_name` (`owner_name`),
  KEY `idx_owner_phone` (`owner_phone`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主主表';

CREATE TABLE IF NOT EXISTS `owner_personal` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `name` varchar(128) NOT NULL COMMENT '姓名',
  `gender` int DEFAULT NULL COMMENT '性别：0=未知，1=男，2=女',
  `id_type` int DEFAULT NULL COMMENT '证件类型：0=身份证，1=护照，2=港澳通行证，3=台胞证',
  `id_no` varchar(64) DEFAULT NULL COMMENT '证件号码',
  `phone` varchar(32) DEFAULT NULL COMMENT '联系电话',
  `payee_name` varchar(64) DEFAULT NULL COMMENT '收款人姓名',
  `payee_phone` varchar(32) DEFAULT NULL COMMENT '收款人电话',
  `payee_id_type` int DEFAULT NULL COMMENT '收款人证件类型',
  `payee_id_no` varchar(64) DEFAULT NULL COMMENT '收款人证件号码',
  `bank_account_name` varchar(128) DEFAULT NULL COMMENT '银行卡开户名',
  `bank_account_no` varchar(64) DEFAULT NULL COMMENT '银行卡号',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '开户行名称',
  `tags` json DEFAULT NULL COMMENT '标签JSON数组',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_personal_company` (`company_id`),
  KEY `idx_owner_personal_name` (`name`),
  KEY `idx_owner_personal_phone` (`phone`),
  KEY `idx_owner_personal_id_no` (`id_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主个人信息表';

CREATE TABLE IF NOT EXISTS `owner_company` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `name` varchar(200) NOT NULL COMMENT '企业名称',
  `uscc` varchar(64) DEFAULT NULL COMMENT '统一社会信用代码',
  `legal_person` varchar(128) DEFAULT NULL COMMENT '法人姓名',
  `legal_person_id_type` int DEFAULT NULL COMMENT '法人证件类型：0=身份证，1=护照，2=港澳通行证，3=台胞证',
  `legal_person_id_no` varchar(64) DEFAULT NULL COMMENT '法人证件号码',
  `contact_name` varchar(128) DEFAULT NULL COMMENT '联系人',
  `contact_phone` varchar(32) DEFAULT NULL COMMENT '联系人电话',
  `payee_name` varchar(64) DEFAULT NULL COMMENT '收款人姓名',
  `payee_phone` varchar(32) DEFAULT NULL COMMENT '收款人电话',
  `payee_id_type` int DEFAULT NULL COMMENT '收款人证件类型',
  `payee_id_no` varchar(64) DEFAULT NULL COMMENT '收款人证件号码',
  `bank_account_name` varchar(128) DEFAULT NULL COMMENT '银行卡开户名',
  `bank_account_no` varchar(64) DEFAULT NULL COMMENT '银行卡号',
  `bank_name` varchar(128) DEFAULT NULL COMMENT '开户行名称',
  `registered_address` varchar(500) DEFAULT NULL COMMENT '注册地址',
  `tags` json DEFAULT NULL COMMENT '标签JSON数组',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_company_company` (`company_id`),
  KEY `idx_owner_company_name` (`name`),
  KEY `idx_owner_company_contact_phone` (`contact_phone`),
  KEY `idx_owner_company_uscc` (`uscc`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主企业信息表';

CREATE TABLE IF NOT EXISTS `owner_contract` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `owner_id` bigint NOT NULL COMMENT '业主ID',
  `cooperation_mode` varchar(32) NOT NULL COMMENT '合作模式：LIGHT_MANAGED=轻托管，MASTER_LEASE=包租',
  `contract_no` varchar(64) NOT NULL COMMENT '合同编号',
  `contract_template_id` bigint DEFAULT NULL COMMENT '合同模板ID',
  `contract_content` longtext COMMENT '合同内容快照',
  `sign_status` int NOT NULL DEFAULT 0 COMMENT '签署状态：0=待签字，1=已签字',
  `sign_type` varchar(32) DEFAULT NULL COMMENT '签约类型：NEW=新签，RENEW=续签',
  `contract_medium` varchar(32) DEFAULT NULL COMMENT '合同介质：ELECTRONIC=电子合同，PAPER=纸质合同',
  `notify_owner` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否通知业主',
  `contract_start` date DEFAULT NULL COMMENT '合同开始日期',
  `contract_end` date DEFAULT NULL COMMENT '合同结束日期',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `approval_status` int NOT NULL DEFAULT 2 COMMENT '审批状态：1=审批中，2=已通过，3=已驳回，4=已撤回',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_contract_no` (`contract_no`),
  KEY `idx_owner_contract_company` (`company_id`),
  KEY `idx_owner_contract_owner` (`owner_id`),
  KEY `idx_owner_contract_mode` (`cooperation_mode`),
  KEY `idx_owner_contract_date` (`contract_start`,`contract_end`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主合同主表';

CREATE TABLE IF NOT EXISTS `owner_contract_house` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `contract_id` bigint NOT NULL COMMENT '业主合同ID',
  `house_id` bigint NOT NULL COMMENT '房源ID',
  `house_name_snapshot` varchar(255) DEFAULT NULL COMMENT '房源名称快照',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_contract_house` (`contract_id`,`house_id`,`deleted`),
  KEY `idx_owner_contract_house_company` (`company_id`),
  KEY `idx_owner_contract_house_house` (`house_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主合同关联房源表';

CREATE TABLE IF NOT EXISTS `owner_settlement_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `contract_id` bigint NOT NULL COMMENT '业主合同ID',
  `contract_house_id` bigint NOT NULL COMMENT '业主合同房源ID',
  `rule_version` int NOT NULL DEFAULT 1 COMMENT '规则版本',
  `income_basis` varchar(32) DEFAULT NULL COMMENT '收入口径：RECEIVED/RECEIVABLE',
  `settlement_mode` varchar(64) DEFAULT NULL COMMENT '结算模式：FIXED/SHARE_GROSS/SHARE_NET/GUARANTEE_PLUS_SHARE/AGENCY',
  `guaranteed_rent_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '保底租金',
  `has_guaranteed_rent` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否有保底租金',
  `commission_mode` varchar(32) DEFAULT NULL COMMENT '佣金方式：RATIO/FIXED',
  `commission_value` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '佣金值',
  `service_fee_mode` varchar(32) DEFAULT NULL COMMENT '服务费方式：RATIO/FIXED',
  `service_fee_value` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '服务费值',
  `management_fee_enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否启用管理费',
  `management_fee_mode` varchar(32) DEFAULT NULL COMMENT '管理费方式：RATIO/FIXED',
  `management_fee_value` decimal(18,2) DEFAULT NULL COMMENT '管理费值',
  `bear_tax_type` varchar(32) DEFAULT NULL COMMENT '税费承担方：PLATFORM/OWNER/SHARED',
  `payment_fee_bear_type` varchar(32) DEFAULT NULL COMMENT '支付手续费承担方式',
  `settlement_timing` varchar(32) DEFAULT NULL COMMENT '分账时间',
  `rent_free_enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否启用免租规则',
  `calc_priority` int DEFAULT NULL COMMENT '计算优先级',
  `effective_start` date DEFAULT NULL COMMENT '生效开始日期',
  `effective_end` date DEFAULT NULL COMMENT '生效结束日期',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `rule_snapshot` longtext COMMENT '规则快照',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_settlement_rule_company` (`company_id`),
  KEY `idx_owner_settlement_rule_contract` (`contract_id`),
  KEY `idx_owner_settlement_rule_house` (`contract_house_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='轻托管结算规则表';

CREATE TABLE IF NOT EXISTS `owner_settlement_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT '公司ID',
  `contract_id` bigint NOT NULL COMMENT '合同ID',
  `contract_house_id` bigint NOT NULL COMMENT '合同房源ID',
  `fee_direction` varchar(16) NOT NULL DEFAULT 'IN' COMMENT '收支方向: IN/OUT',
  `fee_type` varchar(64) NOT NULL COMMENT '费用科目类型',
  `item_name` varchar(64) NOT NULL COMMENT '费用科目名称',
  `transfer_enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否转给业主',
  `transfer_ratio` decimal(5,2) DEFAULT NULL COMMENT '转给业主比例(0-100)',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_settlement_item_company` (`company_id`),
  KEY `idx_owner_settlement_item_contract` (`contract_id`),
  KEY `idx_owner_settlement_item_house` (`contract_house_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='轻托管分账费用科目规则';

CREATE TABLE IF NOT EXISTS `owner_rent_free_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `contract_id` bigint NOT NULL COMMENT '业主合同ID',
  `contract_house_id` bigint NOT NULL COMMENT '业主合同房源ID',
  `enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否启用免租',
  `free_type` varchar(32) DEFAULT NULL COMMENT '免租类型：BUILT_IN/OUTSIDE',
  `start_date` date DEFAULT NULL COMMENT '开始日期',
  `end_date` date DEFAULT NULL COMMENT '结束日期',
  `bear_type` varchar(32) DEFAULT NULL COMMENT '承担方式：PLATFORM/OWNER/SHARED',
  `owner_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '业主承担比例',
  `platform_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '平台承担比例',
  `calc_mode` varchar(32) DEFAULT NULL COMMENT '计算方式：BY_DAYS/FIXED/RATIO',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_rent_free_rule_company` (`company_id`),
  KEY `idx_owner_rent_free_rule_contract` (`contract_id`),
  KEY `idx_owner_rent_free_rule_house` (`contract_house_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='轻托管免租规则表';

CREATE TABLE IF NOT EXISTS `owner_lease_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `contract_id` bigint NOT NULL COMMENT '业主合同ID',
  `rent_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '总月租金',
  `deposit_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '总押金',
  `deposit_months` int NOT NULL DEFAULT 0 COMMENT '押金月数',
  `payment_months` int NOT NULL DEFAULT 1 COMMENT '付款月数',
  `pay_way` varchar(64) DEFAULT NULL COMMENT '付款方式文案',
  `rent_due_type` int DEFAULT NULL COMMENT '收租类型：1=提前，2=固定，3=延后',
  `rent_due_day` int DEFAULT NULL COMMENT '固定收租日',
  `rent_due_offset_days` int DEFAULT NULL COMMENT '收租偏移天数',
  `first_pay_date` date DEFAULT NULL COMMENT '首付日期',
  `handover_date` date DEFAULT NULL COMMENT '交房日期',
  `usage_type` varchar(64) DEFAULT NULL COMMENT '承租用途',
  `billing_start` date DEFAULT NULL COMMENT '计费开始日期',
  `billing_end` date DEFAULT NULL COMMENT '计费结束日期',
  `prorate_type` varchar(32) DEFAULT NULL COMMENT '折算方式：BY_DAYS/FULL_PERIOD',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_lease_rule_contract` (`contract_id`,`deleted`),
  KEY `idx_owner_lease_rule_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='包租规则表';

CREATE TABLE IF NOT EXISTS `owner_lease_fee` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT '公司ID',
  `contract_id` bigint NOT NULL COMMENT '合同ID',
  `fee_type` varchar(64) NOT NULL COMMENT '费用科目类型',
  `fee_name` varchar(64) NOT NULL COMMENT '费用名称',
  `fee_direction` varchar(16) NOT NULL COMMENT '方向: IN/OUT',
  `payment_method` int DEFAULT NULL COMMENT '付款方式',
  `price_method` int DEFAULT NULL COMMENT '金额方式',
  `price_input` decimal(12,2) DEFAULT NULL COMMENT '金额或比例值',
  `sort_order` int NOT NULL DEFAULT 0 COMMENT '排序',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_lease_fee_company` (`company_id`),
  KEY `idx_owner_lease_fee_contract` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='包租其他费用配置';

CREATE TABLE IF NOT EXISTS `owner_lease_free_rule` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `contract_id` bigint NOT NULL COMMENT '业主合同ID',
  `free_type` varchar(32) DEFAULT NULL COMMENT '免租类型：BUILT_IN/OUTSIDE',
  `start_date` date DEFAULT NULL COMMENT '开始日期',
  `end_date` date DEFAULT NULL COMMENT '结束日期',
  `calc_mode` varchar(32) DEFAULT NULL COMMENT '计算方式：FIXED/RATIO',
  `free_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '免租金额',
  `free_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '免租比例',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：1=启用，0=禁用',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_lease_free_rule_company` (`company_id`),
  KEY `idx_owner_lease_free_rule_contract` (`contract_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='包租免租规则表';

CREATE TABLE IF NOT EXISTS `owner_account` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `owner_id` bigint NOT NULL COMMENT '业主ID',
  `account_status` int NOT NULL DEFAULT 1 COMMENT '账户状态：1=启用，0=禁用',
  `available_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '可用金额',
  `frozen_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '冻结金额',
  `pending_settlement_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '待结算金额',
  `total_income_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '累计收入',
  `total_reduction_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '累计扣减',
  `total_withdraw_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '累计提现',
  `version` bigint NOT NULL DEFAULT 0 COMMENT '版本号',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_account_owner` (`owner_id`),
  KEY `idx_owner_account_company` (`company_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主账户表';

CREATE TABLE IF NOT EXISTS `owner_account_flow` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `owner_id` bigint NOT NULL COMMENT '业主ID',
  `biz_type` varchar(64) DEFAULT NULL COMMENT '业务类型',
  `biz_id` bigint DEFAULT NULL COMMENT '业务ID',
  `flow_direction` varchar(32) DEFAULT NULL COMMENT '流水方向',
  `change_type` varchar(64) DEFAULT NULL COMMENT '变动类型',
  `amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动金额',
  `available_before` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动前可用金额',
  `available_after` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动后可用金额',
  `frozen_before` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动前冻结金额',
  `frozen_after` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '变动后冻结金额',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_owner_account_flow_company` (`company_id`),
  KEY `idx_owner_account_flow_owner` (`owner_id`),
  KEY `idx_owner_account_flow_biz` (`biz_type`,`biz_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主账户流水表';

CREATE TABLE IF NOT EXISTS `owner_withdraw_apply` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `company_id` bigint NOT NULL COMMENT 'SaaS企业ID',
  `owner_id` bigint NOT NULL COMMENT '业主ID',
  `apply_no` varchar(64) NOT NULL COMMENT '提现申请单号',
  `apply_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '申请金额',
  `fee_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '手续费',
  `actual_amount` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '实际到账金额',
  `approval_status` int NOT NULL DEFAULT 1 COMMENT '审批状态：1=审批中，2=已通过，3=已驳回，4=已撤回',
  `withdraw_status` int NOT NULL DEFAULT 0 COMMENT '提现状态',
  `payee_name` varchar(128) DEFAULT NULL COMMENT '收款人姓名',
  `payee_account_no` varchar(64) DEFAULT NULL COMMENT '收款账号',
  `payee_bank_name` varchar(128) DEFAULT NULL COMMENT '开户行名称',
  `channel` varchar(32) DEFAULT NULL COMMENT '打款渠道',
  `third_trade_no` varchar(128) DEFAULT NULL COMMENT '第三方交易号',
  `failure_reason` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `applied_at` datetime DEFAULT NULL COMMENT '申请时间',
  `approved_at` datetime DEFAULT NULL COMMENT '审批时间',
  `paid_at` datetime DEFAULT NULL COMMENT '打款时间',
  `deleted` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否删除：0=否，1=是',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_by` bigint DEFAULT NULL COMMENT '更新人',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_owner_withdraw_apply_no` (`apply_no`),
  KEY `idx_owner_withdraw_apply_company` (`company_id`),
  KEY `idx_owner_withdraw_apply_owner` (`owner_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='业主提现申请表';

SET FOREIGN_KEY_CHECKS = 1;
